//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppiTalent_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacante()
        {
            this.AsignacionVacante = new HashSet<AsignacionVacante>();
        }
    
        public int VacanteId { get; set; }
        public string VacanteTitulo { get; set; }
        public Nullable<System.DateTime> VacanteFecha { get; set; }
        public Nullable<int> VacanteAreaId { get; set; }
        public Nullable<int> VacanteLocalidadId { get; set; }
        public string Delegacion_Municipio { get; set; }
        public Nullable<int> VacanteSueldoId { get; set; }
        public string DescripcionVacante { get; set; }
        public Nullable<int> VacanteEstatusId { get; set; }
        public string CometarioVacante { get; set; }
    
        public virtual VacanteArea VacanteArea { get; set; }
        public virtual VacanteEstatus VacanteEstatus { get; set; }
        public virtual VacanteLocalidad VacanteLocalidad { get; set; }
        public virtual VacanteSueldo VacanteSueldo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionVacante> AsignacionVacante { get; set; }
    }
}
